version: '3.8'

services:
  interface:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    depends_on:
      - backend
    networks:
      - app_network
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
